export const actionTypes = {
    FETCH_ALL_EMPLOYEES:'FETCH_ALL_EMPLOYEES',
    FETCH_ALL_EMPLOYEES_SUCCESS:'FETCH_ALL_EMPLOYEES_SUCCESS',
    FETCH_ALL_EMPLOYEES_FAILURE:'FETCH_ALL_EMPLOYEES_FAILURE',
    SET_PAGE_DATA: 'SET_PAGE_DATA'
};