export const actionTypes = {
    FETCH_ALL_EMPLOYEES:'FETCH_ALL_EMPLOYEES',
    FETCH_ALL_EMPLOYEES_SUCCESS:'FETCH_ALL_EMPLOYEES_SUCCESS',
    FETCH_ALL_EMPLOYEES_FAILURE:'FETCH_ALL_EMPLOYEES_FAILURE',
    SET_PAGE_DATA: 'SET_PAGE_DATA',
    SET_PAGE_AND_PAGE_SIZE_EMPLOYEES: "SET_PAGE_AND_PAGE_SIZE_EMPLOYEES",
    OPEN_ADD_EMPLOYEE_MODAL: "OPEN_ADD_EMPLOYEE_MODAL",
    CLOSE_ADD_EMPLOYEE_MODAL: "CLOSE_ADD_EMPLOYEE_MODAL",
    OPEN_EDIT_EMPLOYEE_MODAL: "OPEN_EDIT_EMPLOYEE_MODAL",
    CLOSE_EDIT_EMPLOYEE_MODAL: "CLOSE_EDIT_EMPLOYEE_MODAL"
};