export const actionTypes = {
    SEND_EDIT_USER_DATA_INIT: "SEND_EDIT_USER_DATA",
    SEND_EDIT_USER_DATA_SUCCESS: "SEND_EDIT_USER_DATA_SUCCESS",
    SEND_EDIT_USER_DATA_FAILURE: "SEND_EDIT_USER_DATA_FAILURE",
}