export const actionTypes = {
    SET_PAGE_AND_PAGE_SIZE_PROJECTS: "SET_PAGE_AND_PAGE_SIZE_PROJECTS",
    FETCH_ALL_PROJECTS:'FETCH_ALL_PROJECTS',
    FETCH_ALL_PROJECTS_SUCCESS:'FETCH_ALL_PROJECTS_SUCCESS',
    FETCH_ALL_PROJECTS_FAILURE:'FETCH_ALL_PROJECTS_FAILURE',
    START_LOADER:'START_LOADER',
    STOP_LOADER:'STOP_LOADER',
    OPEN_ADD_PROJECT_MODAL: "OPEN_ADD_PROJECT_MODAL",
    CLOSE_ADD_PROJECT_MODAL: "CLOSE_ADD_PROJECT_MODAL",
    OPEN_EDIT_PROJECT_MODAL: "OPEN_EDIT_PROJECT_MODAL",
    CLOSE_EDIT_PROJECT_MODAL: "CLOSE_EDIT_PROJECT_MODAL",
    CHANGE_PROJECT_TABLE_STATUS: "CHANGE_PROJECT_TABLE_STATUS"
};