export const actionTypes = {
    FETCH_ALL_PROJECTS:'FETCH_ALL_PROJECTS',
    FETCH_ALL_PROJECTS_SUCCESS:'FETCH_ALL_PROJECTS_SUCCESS',
    FETCH_ALL_PROJECTS_FAILURE:'FETCH_ALL_PROJECTS_FAILURE',
    START_LOADER:'START_LOADER',
    STOP_LOADER:'STOP_LOADER',
};