export const actionTypes = {
  AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE_USER_REQUEST',
    LOGOUT_USER: 'LOGOUT_USER',
    GET_ERRORS: 'GET_ERRORS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SET_USER: 'SET_USER',
  };
  