export const actionTypes = {
    FETCH_EMPLOYEE: 'FETCH_EMPLOYEE',
    FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
    FETCH_EMPLOYEE_ERROR: 'FETCH_EMPLOYEE_ERROR',
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE_FAILURE: "DELETE_EMPLOYEE_FAILURE"
};