export const actionTypes = {
    FETCH_ALL_EMPLOYEES_REQUEST: 'FETCH_ALL_EMPLOYEES_REQUEST',
    FETCH_ALL_EMPLOYEES_SUCCESS: 'FETCH_ALL_EMPLOYEES_SUCCESS',
    FETCH_ALL_EMPLOYEES_FAILURE: 'FETCH_ALL_EMPLOYEES_FAILURE',
    CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
  };
  