export const actionTypes = {
    FETCH_PROJECT: 'FETCH_PROJECT',
    FETCH_PROJECT_SUCCESS: 'FETCH_PROJECT_SUCCESS',
    FETCH_PROJECT_ERROR: 'FETCH_PROJECT_ERROR',
    DELETE_PROJECT: "DELETE_PROJECT"
};