export const actionTypes = {
    FETCH_PROJECT: 'FETCH_PROJECT',
    FETCH_PROJECT_SUCCESS: 'FETCH_PROJECT_SUCCESS',
    FETCH_PROJECT_ERROR: 'FETCH_PROJECT_ERROR',
    FETCH_EMPLOYEE: 'FETCH_EMPLOYEE',
    FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
    FETCH_EMPLOYEE_ERROR: 'FETCH_EMPLOYEE_ERROR',
};