export const tableData = [
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },

       {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Projectaaaa 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    {
      key: '1',
      name: 'Project 1fff',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    
    {
      key: '1',
      name: 'Project 1',
      description: 'Description of Project 1',
      duration: '2023-01-01 to 2023-12-31',
      developers: 'John Doe, Jane Smith',
      hourlyRate: 50,
      projectValue: 10000,
      status: 'In progress',
    },
    
  ];