export const actionTypes = {
    FETCH_ALL_EMPLOYEES_REQUEST: 'PROJECT_FETCH_ALL_EMPLOYEES_REQUEST',
    FETCH_ALL_EMPLOYEES_SUCCESS: 'PROJECT_FETCH_ALL_EMPLOYEES_SUCCESS',
    FETCH_ALL_EMPLOYEES_FAILURE: 'PROJECT_FETCH_ALL_EMPLOYEES_FAILURE',
    CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
    UPDATE_DEVELOPER_OPTIONS_REQUEST: 'UPDATE_DEVELOPER_OPTIONS_REQUEST',
    UPDATE_DEVELOPER_OPTIONS_SUCCESS: 'UPDATE_DEVELOPER_OPTIONS_SUCCESS',
    UPDATE_DEVELOPER_OPTIONS_FAILURE: 'UPDATE_DEVELOPER_OPTIONS_FAILURE',
    SET_DEVELOPER_OPTIONS_REQUEST: 'SET_DEVELOPER_OPTIONS_REQUEST',
    SET_DEVELOPER_OPTIONS_SUCCESS: 'SET_DEVELOPER_OPTIONS_SUCCESS',
    SET_DEVELOPER_OPTIONS_FAILURE: 'SET_DEVELOPER_OPTIONS_FAILURE',

  };
  